include:
  - compose.yaml

services:
  backend:
    image: wichteln-backend
    build: ./backend/
    hostname: backend.wichteln.local
    volumes:
      - ~/docker_data/wichteln/config.json:/home/node/backend/config.json
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000

  frontend:
    image: wichteln-frontend
    build: ./frontend/
    hostname: frontend.wichteln.local
    restart: always
    ports:
      - 5173:5173
