services:
  db:
    image: mariadb
    hostname: mariadb.local
    restart: always
    env_file: ~/docker_data/wichteln/mariadb.env
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
