openapi: "3.0.3"
info:
    title: Wichteln API
    version: "1.0"
servers:
    - url: http://localhost:3000
    - url: https://wichteln.desman.xyz
paths:
    /api/user/authenticate:
        post:
            tags:
                - User
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/login-req"
            responses:
                "200":
                    description: User logged in
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/login-res"
                "400":
                    description: Invalid Input
                "500":
                    description: Invalid Input
    /api/user/reset:
        post:
            tags:
                - User
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/email"
            responses:
                "200":
                    description: User logged in
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/login-res"
                "400":
                    description: Invalid Input
                "500":
                    description: Invalid Input
    /api/user/create:
        post:
            description: Add User and login at the same time.
            tags:
                - User
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/addUser-req"
            responses:
                "201":
                    description: User created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/login-res"
                "400":
                    description: Invalid Input
                "401":
                    description: Missing/Wrong JWT
    /api/user:
        get:
            description: Get UserInfo
            tags:
                - User
            responses:
                "200":
                    description: User created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/wholeUser"
                "400":
                    description: Invalid Input
                "401":
                    description: Missing/Wrong JWT
    /api/user/update:
        post:
            description: Update User info.
            tags:
                - User
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/wholeUser"
            responses:
                "200":
                    description: User updated
                "400":
                    description: Invalid Input
                "401":
                    description: Missing/Wrong JWT
    /api/user/delete:
        get:
            tags:
                - User
            responses:
                "200":
                    description: User deleted
                "400":
                    description: Invalid Input
                "401":
                    description: Missing/Wrong JWT
    /api/wichtel:
        post:
            description: Add wichteldata to own user
            tags:
                - Wichtel
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/wichtelData"
            responses:
                "200":
                    description: Wichteldata successfully added
                "400":
                    description: Invalid Input
                "401":
                    description: Missing/Wrong JWT
        get:
            description: Get wichteldata to own user
            tags:
                - Wichtel
            responses:
                "200":
                    description: Wichteldata successfully added
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/wichtelData"
                "400":
                    description: Invalid Input
                "401":
                    description: Missing/Wrong JWT
    /api/wichtel/wichtelee:
        get:
            description: Get wichtelee of user
            tags:
                - Wichtel
            responses:
                "200":
                    description: Wichteldata successfully added
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/wichtelee"
                "400":
                    description: Invalid Input
                "401":
                    description: Missing/Wrong JWT
    /api/wichtel/end:
        post:
            description: Ends the raffle and assigns wichtelees to all participants.
            tags:
                - Wichtel
            responses:
                "200":
                    description: Successfully ended!
                "401":
                    description: Missing/Wrong JWT
                "409":
                    description: Already ended cannot end again
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/error"
                "412":
                    description: Its not yet time to end wichtel
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/error"
    /api/wichtel/enddate:
        get:
            description: Gets the date until when submitting new wichtel data is possible. After that time you should get notified who your wichtelee is.
            tags:
                - Wichtel
            responses:
                "200":
                    description: Fetched wichtel date
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/enddate"
                "401":
                    description: Missing/Wrong JWT

components:
    schemas:
        error:
            type: object
            properties:
                message:
                    type: string
                    example: You did something wrong, here is what!
        email:
            type: object
            properties:
                email:
                    type: string
                    format: email
        addUser-req:
            type: object
            properties:
                username:
                    type: string
                email:
                    type: string
                    format: email
                password:
                    type: string
        wholeUser:
            type: object
            properties:
                username:
                    type: string
                    nullable: true
                email:
                    type: string
                    format: email
                    nullable: true
                password:
                    type: string
                    nullable: true
        wichtelData:
            type: object
            properties:
                address:
                    type: string
                    nullable: true
                wish:
                    type: string
                    nullable: true
        wichtelee:
            type: object
            properties:
                username:
                    type: string
                    nullable: false
                address:
                    type: string
                    nullable: true
                wish:
                    type: string
                    nullable: true

        enddate:
            type: string
            example: "13.12.2024T12:00:00Z"
            nullable: false
        login-req:
            type: object
            properties:
                username:
                    type: string
                password:
                    type: string
        login-res:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                email:
                    type: string
                    format: email
                username:
                    type: string
                token:
                    type: string
